version: '3.7'

services:
  elias-profile-web-app:
    image: localhost:5000/elias-profile-web-app:v1
    container_name: elias-profile-web-app
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "128M"
    ports:
      - "127.0.0.1:8085:80"
      - "172.17.0.1:8085:80"
    volumes:
      - "/opt/logs/:/opt/logs"

